theme: jekyll-theme-cayman
title: Erick Jara's Portfolio
author: Erick Jara
email: erick_jara@alumni.brown.edu
description: Feel free to bookmark this to keep an eye on my project updates

# social links
github_username: efjara

show_excerpts: true 

